version: '3.1'
services:
  stock-market-trading:
    container_name: stock-market-trading
    image: docker/stock-market-trading
    build:
      context: .
      dockerfile: docker/stock-market-trading/Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
  stock-market-service:
    container_name: stock-market-service
    image: docker/stock-market-service
    build:
      context: .
      dockerfile: docker/stock-market-service/Dockerfile
    ports:
      - "8081:8080"
      - "5006:5005"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stock_market_trading
      - POSTGRES_USER=stock_market_trading
      - POSTGRES_DB=stock_market_trading
