INSERT INTO instrument VALUES(1, 'CDPROJEKT');
INSERT INTO instrument VALUES(2, 'TESLA');
INSERT INTO instrument VALUES(3, 'PGE');

INSERT INTO order_type VALUES(1, 'BUY');
INSERT INTO order_type VALUES(2, 'SELL');
